 name: Automate Script Execution

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the top of the hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Install any dependencies if you have a requirements.txt

      - name: Run Automate Script
        run: |
          python automate.py  # Execute your automate.py script
